apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-test-com
spec:
  dnsNames:
    - '*.upthestack.io'
  issuerRef:
    name: letsencrypt-ionos-staging
  secretName: example-test-com-tls
